name: CI
on:
  push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        with:
          node-version: 22
          cache: npm
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm test
